[package]
name = "smallbank"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
zipf = "7.0.1"
rand_distr = "0.4.3"
bytes = "1.0.1"